# Generated by Django 5.2.17 on 2026-09-08 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Max guests this room type sleeps.')),
                ('night_rate', models.DecimalField(decimal_places=2, help_text='Full-night rate in ZMW (e.g. 450.00).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('short_time_rate', models.DecimalField(decimal_places=2, help_text='Short-time / day-use rate in ZMW (e.g. 200.00).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('short_time_hours', models.PositiveIntegerField(default=4, help_text='Number of hours covered by the short-time rate.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire this room type without deleting it (keeps historical bookings/rates intact).')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('dirty', 'Dirty'), ('clean', 'Clean'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Archived (soft-deleted) rooms are hidden from booking but keep their history.')),
                ('notes', models.TextField(blank=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
    ]
